name: CI

on:
  push:
    branches: [ main ]

jobs:

 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          touch .env
          docker-compose --profile test_profile up --exit-code-from lint lint