name: CI

on:
  push:
    branches: [ main ]

jobs:

 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: postgres
          envkey_POSTGRES_PASSWORD: postgres
          envkey_POSTGRES_NAME: postgres
          envkey_POSTGRES_HOST: db
          envkey_POSTGRES_PORT: 5432
          envkey_SECRET_KEY: secret_key
          envkey_STRIPE_SECRET_KEY : secret_stripe_key
          envkey_STRIPE_PUBLIC_KEY : public_stripe_key
          directory: ${GITHUB_WORKSPACE}
          file_name: .env
      - uses: actions/checkout@v2
      - name: Run linter
        run: docker-compose --profile test_profile up --exit-code-from lint lint